ProyectoIntegrador/ProyectoIntegrador/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoIntegrador.Data;
using ProyectoIntegrador.Models;

namespace ProyectoIntegrador.Controllers
{
    public class CarritoController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public CarritoController(MvcTiendaContexto context)
        {
            _context = context;
        }

        // GET: Carrito
        public async Task<IActionResult> Index()
        {
            // int intNumeroPedido = 0;
            // string numeroPedido = httpContext.Session.GetString("NumPedido");
            // if (numeroPedido == null)
            // {
            // return view("CarritoVacio"); 
            // }
            // intNumeroPedido = Convert.ToInt32(numeroPedido);
            // var pedido = await_context.Pedidos
            // .Include(x =>x.Cliente)
            // .Include(x =>x.Estado)
            // .Include(x=>x.Detalles)
            // .Include(x =>x.Producto)
            // .ThenInclude(x=>x.Producto)+.FirtsOrDefaultAsync(e => e.Id == intNumeroPedido);

            // if(pedido == null)
            // {
            // return NotFound();
            // }
            // return View(pedido);
            // }

            //GET Carrito vacío
            
            // public ActionResult CarritoVacio()
            // {
            // return View();
            // }

            // POST Detalles/EliminarLinea

            // [httpPost]
            // [ValidateAntiForgeryToken ]
            // public async Task<IActionResult> EliminarLinea(int id)
            // {
            // var detalle = await_context.Detalles.FindAsync(id);
            // await _context.SaveChangesAsync();

            // return RedirectToAction(nameof(Index));
            // }


            // GET CarritoMasCantidad

            // private bool DetallesExists(int id)
            // {
            // return _context.Detalles.Any(p => p.ID == Id);
            // }

            // public asyn Task<IActionResult>MasCantidad (int ? id)
            // {
            // if (id == null)
            // {
            // return NotFound();
            // }

            // var detalle = await _context.Detalles.FindAsync(id);
            // detalle.Cantidad = detalle.CAntidad + 1;
            
            // if(ModelState.IsValid)
            // {
            // try
            // {
            // _context.UpDate(detalle);
            // await _context.SaveChangesAsync();
            // }
            // catch (DbpdateConcurrencyException)
            // {
            // if(!DetalleExists(detalle.id))
            // {
            // return NotFound();
            // }
            // else
            // {
            // throw;
            // }
            // }
            // }
            // return RedirectToAction(nameof(Index));
            // }


            // GET carrito/MenosCantidad

            // public async Task<ActionResult>MenosCantidad(int ? id)
            // {
            // if(id == null)
            // {
            // return NotFound();
            // }

            // var detalle = await_context.Detalles.FindAsync(id);
            // detalle.Cantidad = detalle.Cantidad - 1;
            // if(ModelState.IsValid)
            // {
            // try
            // {
            // _context.Update(detalle);
            // await_context.SaveChangeAsync();
            // }
            // catch(DbUpdateConcurrencyException)
            // {
            // if(!DetalleExisists(detalle.id))
            // {
            // return NotFound();
            // }
            // else
            // {
            // throw;
            // }
            // }
            // }
            // return RedirectToAction(nameof(Index));
            // }


            // POST Carrito/ConfirmarPedido

            // [HttpPost]
            // [ValidateAntiForgeryToken]
            // public async Task<IActionResult> ConfirmarPedido(int ? id)
            // {
            // if(id == null)
            // {
            // return NotFound();
            // }

            // var pedido = await_context.Pedidos.FindAsync(id);

            // se cambia el estado del pedido a confirmado

            // pedido.EstadoId = 2;
            // pedido.Confirmado = DateTime.Now;

            // if(ModelState.IsValid)
            // {
            // try
            // {
            // _context.Update(pedido);
            // await_context.SaveChangesAsync();
            // Al confirmar el pedido se pone la variable de sesion del pedido actual
            // HttpContext.Session.Remove("NumPedido");
            // }
            // catch(DbUpdateConcurrencyException)
            // {
            // if(!PedidoExists(pedido.id)
            // {
            // return NotFound();
            // }
            // else
            // {
            // throw;
            // }
            // }
            // }
            // return RedirectToAction(nameof(Index), "Escaparate");
            // }

            // private bool PedidoExists(int id)
            // {
            // return _context.Pedidos.Any(p=>p.Id ==id);
            // }
            // }
            // }





            string emailUsuario = User.Identity.Name;
            int ClienteId;
            Pedido pedidoActual = null;
            var pendiente = await _context.Estados
                .Where(e => e.Descripcion == "Pendiente")
                .FirstOrDefaultAsync();

            var cliente = await _context.Clientes
                .Where(e => e.Email == emailUsuario)
                .FirstOrDefaultAsync();

            if (cliente != null)
            {
                ClienteId = cliente.Id;

                pedidoActual = await _context.Pedidos
                    .Include(p => p.Detalles)
                        .ThenInclude(x => x.Producto)
                    .Include(p => p.Cliente)
                    .Where(e => e.ClienteId == ClienteId && e.EstadoId == pendiente.Id)
                    .FirstOrDefaultAsync();
            }

            return View(pedidoActual);
        }

        public async Task<ActionResult> MenosCantidad(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalle = await _context.Detalles.FindAsync(id);
            detalle.Cantidad = detalle.Cantidad - 1;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetallesExists(detalle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET CarritoMasCantidad

        private bool DetallesExists(int id)
        {
            return _context.Detalles.Any(p => p.Id == id);
        }

        public async Task<IActionResult>MasCantidad (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalle = await _context.Detalles.FindAsync(id);
            detalle.Cantidad = detalle.Cantidad + 1;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetallesExists(detalle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }
        // POST Detalles/EliminarLinea

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarLinea(int id)
        {
            var detalle = await _context.Detalles.FindAsync(id);
            _context.Detalles.Remove(detalle);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // POST Carrito/ConfirmarPedido

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmarPedido(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pedido pedido = await _context.Pedidos
                .Include(p => p.Detalles)
                .ThenInclude(p => p.Producto)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            //se cambia el estado del pedido a confirmado

            var confirmado = await _context.Estados
            .Where(e => e.Descripcion == "Confirmado")
            .FirstOrDefaultAsync();
            pedido.EstadoId = confirmado.Id;
            pedido.Confirmado = DateTime.Now;
            // recorrer las lineas del pedido y para cada línea del pedido,
            // obtener de la BD el producto al que está haciendo referencia y restarle la cantidad de unidades

            foreach( Detalle detalle  in pedido.Detalles)
            {
                var producto = await _context.Productos
                    .Where(e => e.Id == detalle.ProductoId)
                    .FirstOrDefaultAsync();
                producto.Stock = producto.Stock - detalle.Cantidad;

                _context.Update(producto);
            }
            if (ModelState.IsValid)
            {
                try
                {

ProyectoIntegrador/ProyectoIntegrador/Controllers/EstadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoIntegrador.Data;
using ProyectoIntegrador.Models;

namespace ProyectoIntegrador.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class EstadosController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public EstadosController(MvcTiendaContexto context)
        {
            _context = context;
        }

        // GET: Estados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estados.ToListAsync());
        }

        // GET: Estados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // GET: Estados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados.FindAsync(id);
            if (estado == null)
            {
                return NotFound();
            }
            return View(estado);
        }

        // POST: Estados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion")] Estado estado)
        {
            if (id != estado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoExists(estado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // POST: Estados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estado = await _context.Estados.FindAsync(id);
            _context.Estados.Remove(estado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoExists(int id)
        {
            return _context.Estados.Any(e => e.Id == id);
        }
    }
}

ProyectoIntegrador/ProyectoIntegrador/Controllers/MisDatosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoIntegrador.Data;
using ProyectoIntegrador.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoIntegrador.Controllers
{
    [Authorize(Roles = "Usuario")]
    public class MisDatosController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public MisDatosController(MvcTiendaContexto context)
        {
            _context = context;
        }
        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit()
        {
            string emailUsuario = User.Identity.Name;
            if (emailUsuario == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Where(e => e.Email == emailUsuario)
                .FirstOrDefaultAsync();

            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Email,Telefono,Direccion,Poblacion,CodigoPostal,Nif")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction("Index","Home");
            }
            return View(cliente);
        }
    }
}

ProyectoIntegrador/ProyectoIntegrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto Integrador</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Escaparate" asp-action="Index">ProyectoIntegrador</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Escaparate" asp-action="Index">Escaparate</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""
                                   asp-controller="Carrito" asp-action="Index">Carrito</a>
                            </li>

                            @if (User.IsInRole("Usuario"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="MisDatos" asp-action="Edit">Mis datos</a>
                                </li>
                            }
                            @if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Estados" asp-action="Index">Estados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Categorias" asp-action="Index">Categorías</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Productos" asp-action="Index">Productos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Clientes" asp-action="Index">Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                                </li>
                                <!--
                                    DEJO ESTO COMENTADO PORQUE HICE COPIAR/PEGAR DE LA PRÁCTICA 6 Y TENGO QUE VER SI ME VA A SERVIR O NO...CREO QUE NO...
                                    <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                    asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                    </li>
                                -->
                            }
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Proyecto Integrador - <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>